"""Tests for vastly.ssh -- SSH config generation, include management, and helpers."""

from __future__ import annotations

import socket
import subprocess
from pathlib import Path

import pytest

import vastly.ssh
from vastly.ssh import (
    clear_ssh_configs,
    ensure_ssh_include,
    find_available_port,
    forget_host_key,
    host_key_changed,
    is_port_available,
    run_ssh,
    set_forward_agent,
    ssh_program,
    write_ssh_config,
)


class TestPortHelpers:
    def test_detects_port_in_use(self):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.bind(("127.0.0.1", 0))
            port = sock.getsockname()[1]
            assert not is_port_available(port)

    def test_detects_port_available(self):
        # Bind then release -- port should be available immediately after
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.bind(("127.0.0.1", 0))
            port = sock.getsockname()[1]
        assert is_port_available(port)

    def test_find_available_port_skips_excluded(self):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.bind(("127.0.0.1", 0))
            port = sock.getsockname()[1]
        # Port is free, but excluded -- should skip to port + 1
        result = find_available_port(port, {port})
        assert result == port + 1

    def test_find_available_port_raises_when_exhausted(self):
        with pytest.raises(RuntimeError, match="No available port"):
            find_available_port(65536)


class TestSetForwardAgent:
    def _write(self, tmp_path, monkeypatch, name="gpu"):
        monkeypatch.setattr("vastly.ssh.SSH_CONFIG_DIR", tmp_path)
        write_ssh_config(
            name,
            inst_id=1,
            host="10.0.0.1",
            port=22,
            user="root",
            key_path=None,
            local_forwards=[],
        )
        return tmp_path / name

    def test_turns_forwarding_off_and_on(self, tmp_path, monkeypatch):
        path = self._write(tmp_path, monkeypatch)
        set_forward_agent("gpu", False)
        assert "    ForwardAgent no" in path.read_text()
        set_forward_agent("gpu", True)
        assert "    ForwardAgent yes" in path.read_text()

    def test_leaves_non_vastly_files_alone(self, tmp_path, monkeypatch):
        monkeypatch.setattr("vastly.ssh.SSH_CONFIG_DIR", tmp_path)
        path = tmp_path / "mine"
        path.write_text("Host mine\n    ForwardAgent yes\n")
        set_forward_agent("mine", False)
        assert "ForwardAgent yes" in path.read_text()

    def test_missing_file_is_a_no_op(self, tmp_path, monkeypatch):
        monkeypatch.setattr("vastly.ssh.SSH_CONFIG_DIR", tmp_path)
        set_forward_agent("nope", False)


class TestSshConfig:
    def test_generates_valid_config(self, tmp_path, monkeypatch):
        monkeypatch.setattr("vastly.ssh.SSH_CONFIG_DIR", tmp_path)

        write_ssh_config(
            "1xrtx4090-tw",
            inst_id=1,
            host="192.168.1.1",
            port=22222,
            user="root",
            key_path=None,
            local_forwards=[],
        )

        content = (tmp_path / "1xrtx4090-tw").read_text()
        assert content.startswith("# Generated by vastly")
        assert "Host 1xrtx4090-tw" in content
        assert "HostName 192.168.1.1" in content
        assert "Port 22222" in content
        assert "User root" in content
        assert "ForwardAgent yes" in content

    def test_forward_agent_can_be_disabled(self, tmp_path, monkeypatch):
        monkeypatch.setattr("vastly.ssh.SSH_CONFIG_DIR", tmp_path)
        write_ssh_config(
            "gpu",
            inst_id=1,
            host="10.0.0.1",
            port=22,
            user="root",
            key_path=None,
            local_forwards=[],
            forward_agent=False,
        )
        content = (tmp_path / "gpu").read_text()
        assert "ForwardAgent no" in content
        assert "ForwardAgent yes" not in content

    def test_includes_identity_file(self, tmp_path, monkeypatch):
        monkeypatch.setattr("vastly.ssh.SSH_CONFIG_DIR", tmp_path)

        write_ssh_config(
            "test",
            inst_id=1,
            host="10.0.0.1",
            port=22,
            user="root",
            key_path="C:\\Users\\me\\.ssh\\id_rsa",
            local_forwards=[],
        )

        content = (tmp_path / "test").read_text()
        assert 'IdentityFile "C:/Users/me/.ssh/id_rsa"' in content

    def test_includes_local_forward(self, tmp_path, monkeypatch):
        monkeypatch.setattr("vastly.ssh.SSH_CONFIG_DIR", tmp_path)

        write_ssh_config(
            "test",
            inst_id=1,
            host="10.0.0.1",
            port=22,
            user="root",
            key_path=None,
            local_forwards=[(8080, 8080)],
        )

        content = (tmp_path / "test").read_text()
        assert "LocalForward 8080 localhost:8080" in content

    def test_includes_multiple_local_forwards(self, tmp_path, monkeypatch):
        monkeypatch.setattr("vastly.ssh.SSH_CONFIG_DIR", tmp_path)

        write_ssh_config(
            "test",
            inst_id=1,
            host="10.0.0.1",
            port=22,
            user="root",
            key_path=None,
            local_forwards=[(8080, 8080), (3000, 3000)],
        )

        content = (tmp_path / "test").read_text()
        assert "LocalForward 8080 localhost:8080" in content
        assert "LocalForward 3000 localhost:3000" in content

    def test_omits_identity_file_when_empty_string(self, tmp_path, monkeypatch):
        monkeypatch.setattr("vastly.ssh.SSH_CONFIG_DIR", tmp_path)
        write_ssh_config(
            "test",
            inst_id=1,
            host="10.0.0.1",
            port=22,
            user="root",
            key_path="",
            local_forwards=[],
        )
        content = (tmp_path / "test").read_text()
        assert "IdentityFile" not in content

    def test_no_local_forward_lines_when_empty(self, tmp_path, monkeypatch):
        monkeypatch.setattr("vastly.ssh.SSH_CONFIG_DIR", tmp_path)
        write_ssh_config(
            "test",
            inst_id=1,
            host="10.0.0.1",
            port=22,
            user="root",
            key_path=None,
            local_forwards=[],
        )
        content = (tmp_path / "test").read_text()
        assert "LocalForward" not in content


class TestHostKeys:
    """Host keys are trusted on first use and checked after, per instance."""

    def _config(self, tmp_path, monkeypatch, name, inst_id, host):
        monkeypatch.setattr("vastly.ssh.SSH_CONFIG_DIR", tmp_path)
        write_ssh_config(
            name,
            inst_id=inst_id,
            host=host,
            port=22,
            user="root",
            key_path=None,
            local_forwards=[],
        )
        return (tmp_path / name).read_text()

    def test_checked_under_the_instance_id_in_vastlys_own_file(
        self, tmp_path, monkeypatch
    ):
        content = self._config(tmp_path, monkeypatch, "gpu", 42, "10.0.0.1")

        known_hosts = str(vastly.ssh.KNOWN_HOSTS).replace("\\", "/")
        assert "HostKeyAlias vastly-42" in content
        assert f'UserKnownHostsFile "{known_hosts}"' in content
        assert "StrictHostKeyChecking accept-new" in content
        assert "StrictHostKeyChecking no" not in content

    def test_same_instance_keeps_its_key_across_names_and_addresses(
        self, tmp_path, monkeypatch
    ):
        first = self._config(tmp_path, monkeypatch, "gpu", 42, "10.0.0.1")
        alias = self._config(tmp_path, monkeypatch, "train", 42, "ssh4.vast.ai")
        other = self._config(tmp_path, monkeypatch, "other", 7, "10.0.0.1")

        assert "HostKeyAlias vastly-42" in first
        assert "HostKeyAlias vastly-42" in alias
        assert "HostKeyAlias vastly-7" in other

    def test_forget_removes_only_that_instance(self, tmp_path, monkeypatch):
        known_hosts = tmp_path / "known_hosts"
        known_hosts.write_text(
            "vastly-4 ssh-ed25519 AAAA4\n"
            "vastly-42 ssh-ed25519 AAAA42\n"
            "vastly-42 ecdsa-sha2-nistp256 BBBB42\n"
            "vastly-420 ssh-ed25519 AAAA420\n",
            encoding="utf-8",
        )
        monkeypatch.setattr("vastly.ssh.KNOWN_HOSTS", known_hosts)

        forget_host_key(42)

        assert known_hosts.read_text(encoding="utf-8") == (
            "vastly-4 ssh-ed25519 AAAA4\nvastly-420 ssh-ed25519 AAAA420\n"
        )

    def test_forget_without_a_file_is_a_no_op(self, tmp_path, monkeypatch):
        monkeypatch.setattr("vastly.ssh.KNOWN_HOSTS", tmp_path / "known_hosts")
        forget_host_key(42)
        assert not (tmp_path / "known_hosts").exists()

    def test_detects_ssh_refusing_a_changed_key(self):
        assert host_key_changed(
            "@@@ WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED! @@@\n"
            "Host key verification failed.\r\n"
        )
        assert not host_key_changed("Connection refused")


class TestSshProgram:
    """On Windows, vastly runs Windows' own OpenSSH, like VS Code does."""

    def test_prefers_windows_openssh(self, tmp_path, monkeypatch):
        (tmp_path / "ssh.exe").write_text("")
        monkeypatch.setattr("vastly.ssh._WINDOWS_OPENSSH", tmp_path)

        assert ssh_program("ssh") == str(tmp_path / "ssh.exe")
        assert ssh_program("scp") == "scp"  # not installed there: use PATH

    def test_uses_path_elsewhere(self):
        assert ssh_program("ssh") == "ssh"

    def test_run_ssh_uses_it(self, tmp_path, monkeypatch):
        (tmp_path / "ssh.exe").write_text("")
        monkeypatch.setattr("vastly.ssh._WINDOWS_OPENSSH", tmp_path)
        seen = []

        def fake_run(cmd, **kwargs):
            seen.append(cmd)
            return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")

        monkeypatch.setattr("vastly.ssh.subprocess.run", fake_run)
        run_ssh("gpu", "true")
        assert seen[0][0] == str(tmp_path / "ssh.exe")


class TestEnsureSshInclude:
    def test_creates_config_with_include(self, tmp_path, monkeypatch):
        monkeypatch.setattr(Path, "home", lambda: tmp_path)

        ensure_ssh_include()

        content = (tmp_path / ".ssh" / "config").read_text()
        assert "Include vast.d/*" in content

    def test_prepends_to_existing_config(self, tmp_path, monkeypatch):
        monkeypatch.setattr(Path, "home", lambda: tmp_path)
        ssh_dir = tmp_path / ".ssh"
        ssh_dir.mkdir()
        (ssh_dir / "config").write_text(
            "Host myserver\n    HostName 10.0.0.1\n", encoding="utf-8"
        )

        ensure_ssh_include()

        content = (ssh_dir / "config").read_text()
        assert content.startswith("Include vast.d/*")
        assert "Host myserver" in content

    def test_does_not_duplicate_include(self, tmp_path, monkeypatch):
        monkeypatch.setattr(Path, "home", lambda: tmp_path)
        ssh_dir = tmp_path / ".ssh"
        ssh_dir.mkdir()
        (ssh_dir / "config").write_text(
            "Include vast.d/*\nHost myserver\n", encoding="utf-8"
        )

        ensure_ssh_include()

        content = (ssh_dir / "config").read_text()
        assert content.count("Include vast.d/*") == 1

    def test_detects_existing_backslash_include(self, tmp_path, monkeypatch):
        """Windows-style backslash in existing Include should be detected."""
        monkeypatch.setattr(Path, "home", lambda: tmp_path)
        ssh_dir = tmp_path / ".ssh"
        ssh_dir.mkdir()
        (ssh_dir / "config").write_text(
            "Include vast.d\\*\nHost myserver\n", encoding="utf-8"
        )

        ensure_ssh_include()

        content = (ssh_dir / "config").read_text()
        assert content.count("Include") == 1


class TestSshConfigManagement:
    def test_clear_removes_generated_files(self, tmp_path, monkeypatch):
        monkeypatch.setattr("vastly.ssh.SSH_CONFIG_DIR", tmp_path)
        (tmp_path / "host1").write_text(
            "# Generated by vastly -- do not edit\nHost host1\n"
        )
        (tmp_path / "host2").write_text(
            "# Generated by vastly -- do not edit\nHost host2\n"
        )

        clear_ssh_configs()

        assert list(tmp_path.iterdir()) == []

    def test_clear_preserves_non_generated_files(self, tmp_path, monkeypatch):
        monkeypatch.setattr("vastly.ssh.SSH_CONFIG_DIR", tmp_path)
        (tmp_path / "host1").write_text(
            "# Generated by vastly -- do not edit\nHost host1\n"
        )
        (tmp_path / "custom").write_text("Host myserver\n    HostName 10.0.0.1\n")

        clear_ssh_configs()

        remaining = [f.name for f in tmp_path.iterdir()]
        assert remaining == ["custom"]

    def test_clear_skips_directories(self, tmp_path, monkeypatch):
        monkeypatch.setattr("vastly.ssh.SSH_CONFIG_DIR", tmp_path)
        (tmp_path / "host1").write_text(
            "# Generated by vastly -- do not edit\nHost host1\n"
        )
        (tmp_path / "subdir").mkdir()

        clear_ssh_configs()

        remaining = [f.name for f in tmp_path.iterdir()]
        assert remaining == ["subdir"]


class TestRunScp:
    def test_recursive_flag_added(self, monkeypatch):
        """run_scp with recursive=True should include -r in the command."""
        captured_cmd = []

        def fake_run(cmd, **kwargs):
            captured_cmd.extend(cmd)
            return subprocess.CompletedProcess([], 0, stdout="", stderr="")

        monkeypatch.setattr("vastly.ssh.subprocess.run", fake_run)
        from vastly.ssh import run_scp

        run_scp("/tmp/src", "host:/tmp/dest", recursive=True)
        assert "-r" in captured_cmd

    def test_no_recursive_flag_by_default(self, monkeypatch):
        """run_scp without recursive should not include -r."""
        captured_cmd = []

        def fake_run(cmd, **kwargs):
            captured_cmd.extend(cmd)
            return subprocess.CompletedProcess([], 0, stdout="", stderr="")

        monkeypatch.setattr("vastly.ssh.subprocess.run", fake_run)
        from vastly.ssh import run_scp

        run_scp("/tmp/src", "host:/tmp/dest")
        assert "-r" not in captured_cmd


class TestOutputDecoding:
    """SSH output is decoded as UTF-8, and timeouts always return text."""

    def test_run_ssh_decodes_utf8(self, monkeypatch):
        seen = {}

        def fake_run(cmd, **kwargs):
            seen.update(kwargs)
            return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")

        monkeypatch.setattr("vastly.ssh.subprocess.run", fake_run)
        run_ssh("gpu", "echo hi")
        assert seen["encoding"] == "utf-8" and seen["errors"] == "replace"

    @pytest.mark.parametrize("output", [b"partial \xc3\xa9", "partial é"])
    def test_timeout_output_is_text(self, monkeypatch, output):
        """TimeoutExpired carries bytes on macOS/Linux even with text=True."""
        from vastly.ssh import run_scp

        def hang(cmd, **kwargs):
            raise subprocess.TimeoutExpired(cmd, 30, output=output, stderr=None)

        monkeypatch.setattr("vastly.ssh.subprocess.run", hang)
        for result in (run_ssh("gpu", "sleep 99"), run_scp("a", "gpu:b")):
            assert result.returncode == 1
            assert result.stdout == "partial é"
            assert result.stderr == "timeout"
