"""SSH config management, port helpers, and SSH/SCP wrappers."""

from __future__ import annotations

import os
import re
import socket
import subprocess
import sys
from pathlib import Path

import vastly
from vastly import dim

SSH_CONFIG_DIR = Path.home() / ".ssh" / "vast.d"

# Instance host keys, stored under "vastly-<instance id>" (see write_ssh_config)
KNOWN_HOSTS = Path.home() / ".vastly" / "known_hosts"

# Windows' own OpenSSH: the one VS Code and the Windows ssh-agent service use.
# Git Bash puts its own ssh first on PATH, with a separate agent.
_WINDOWS_OPENSSH = (
    Path(os.environ.get("SYSTEMROOT", r"C:\Windows")) / "System32" / "OpenSSH"
    if sys.platform == "win32"
    else None
)

_GENERATED_HEADER = "# Generated by vastly -- do not edit"


def _atomic_write(path: Path, content: str) -> None:
    """Write content to path atomically via temp-file-then-rename."""
    tmp = path.parent / (path.name + ".vastly-tmp")
    tmp.write_text(content, encoding="utf-8")
    try:
        tmp.replace(path)
    except OSError:
        # Windows: replace() fails if target is open; fall back to delete+rename
        path.unlink(missing_ok=True)
        tmp.rename(path)


# Quick probes (echo ok, test -f, find): fail fast on dead connections
SSH_OPTS = [
    "-o",
    "ConnectTimeout=10",
    "-o",
    "ServerAliveInterval=5",
    "-o",
    "ServerAliveCountMax=2",
]

# Long-running commands (setup script): allow more time between keepalives
SSH_SETUP_OPTS = [
    "-o",
    "ConnectTimeout=10",
    "-o",
    "ServerAliveInterval=15",
    "-o",
    "ServerAliveCountMax=4",
]


def ssh_program(name: str) -> str:
    """ssh or scp: Windows' own OpenSSH on Windows, else the one on PATH."""
    if _WINDOWS_OPENSSH and (_WINDOWS_OPENSSH / f"{name}.exe").is_file():
        return str(_WINDOWS_OPENSSH / f"{name}.exe")
    return name


def host_key_alias(inst_id: int) -> str:
    """The name an instance's host key is stored under, whatever its address."""
    return f"vastly-{inst_id}"


def _config_path(path: Path | str) -> str:
    """A path for an SSH config file: forward slashes (fine on Windows), quoted."""
    return '"' + str(path).replace("\\", "/") + '"'


def is_port_available(port: int) -> bool:
    """Check if a local TCP port is available to bind."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        try:
            sock.bind(("127.0.0.1", port))
            return True
        except OSError:
            return False


def find_available_port(start: int, exclude: set[int] | None = None) -> int:
    """Find the first available port starting from *start*, skipping *exclude*."""
    exclude = exclude or set()
    port = start
    while port <= 65535 and (not is_port_available(port) or port in exclude):
        port += 1
    if port > 65535:
        raise RuntimeError(f"No available port found starting from {start}")
    return port


def ensure_ssh_include() -> None:
    """Ensure ~/.ssh/config contains 'Include vast.d/*'."""
    ssh_dir = Path.home() / ".ssh"
    ssh_config = ssh_dir / "config"
    include_line = "Include vast.d/*"

    if ssh_config.exists():
        content = ssh_config.read_text(encoding="utf-8")
        if not re.search(r"Include\s+vast\.d[/\\]\*", content):
            _atomic_write(ssh_config, f"{include_line}\n{content}")
            print(dim(f"Added '{include_line}' to {ssh_config}"))
    else:
        ssh_dir.mkdir(parents=True, exist_ok=True)
        _atomic_write(ssh_config, include_line + "\n")
        print(dim(f"Created {ssh_config} with '{include_line}'"))


def write_ssh_config(
    name: str,
    *,
    inst_id: int,
    host: str,
    port: int,
    user: str,
    key_path: str | None,
    local_forwards: list[tuple[int, int]],
    forward_agent: bool = True,
) -> None:
    """Write a single SSH config file to ~/.ssh/vast.d/<name>."""
    SSH_CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    lines = [
        _GENERATED_HEADER,
        "# The instance's host key is trusted on first connection and checked after",
        "# that. It's stored under the instance ID, so a new address (after a",
        "# restart) or a recycled IP doesn't matter. Agent forwarding lets git on",
        "# the instance use your local SSH key; it's off when it uses a deploy key.",
        f"Host {name}",
        f"    HostName {host}",
        f"    Port {port}",
        f"    User {user}",
        f"    ForwardAgent {'yes' if forward_agent else 'no'}",
        f"    HostKeyAlias {host_key_alias(inst_id)}",
        f"    UserKnownHostsFile {_config_path(KNOWN_HOSTS)}",
        "    StrictHostKeyChecking accept-new",
        "    CheckHostIP no",
        "    HashKnownHosts no",
        "    ServerAliveInterval 30",
        "    ServerAliveCountMax 4",
        "    LogLevel ERROR",
    ]

    if key_path:
        lines.append(f"    IdentityFile {_config_path(key_path)}")

    for local_port, remote_port in local_forwards:
        lines.append(f"    LocalForward {local_port} localhost:{remote_port}")

    config_file = SSH_CONFIG_DIR / name
    _atomic_write(config_file, "\n".join(lines) + "\n")


def set_forward_agent(name: str, enabled: bool) -> None:
    """Turn agent forwarding on/off in an existing vastly-generated SSH config."""
    config_file = SSH_CONFIG_DIR / name
    if not config_file.exists():
        return
    content = config_file.read_text(encoding="utf-8")
    if not content.startswith(_GENERATED_HEADER):
        return
    value = "yes" if enabled else "no"
    updated = re.sub(
        r"(?m)^([ \t]*)ForwardAgent[ \t]+\S+$", rf"\g<1>ForwardAgent {value}", content
    )
    if updated != content:
        _atomic_write(config_file, updated)


def forget_host_key(inst_id: int) -> None:
    """Remove a destroyed instance's host key from vastly's known_hosts."""
    try:
        lines = KNOWN_HOSTS.read_text(encoding="utf-8").splitlines(keepends=True)
    except OSError:
        return
    alias = host_key_alias(inst_id)
    kept = [ln for ln in lines if alias not in ln.split(" ", 1)[0].split(",")]
    if len(kept) != len(lines):
        _atomic_write(KNOWN_HOSTS, "".join(kept))


def host_key_changed(stderr: str) -> bool:
    """Whether ssh refused to connect because the host key changed."""
    return "Host key verification failed" in stderr


def clear_ssh_configs() -> None:
    """Remove vastly-generated files from ~/.ssh/vast.d/."""
    if SSH_CONFIG_DIR.exists():
        for f in SSH_CONFIG_DIR.iterdir():
            if not f.is_file():
                continue
            first_line = f.read_text(encoding="utf-8").split("\n", 1)[0]
            if first_line.startswith("# Generated by vastly"):
                f.unlink()


def prune_ssh_configs(keep: set[str]) -> None:
    """Remove vastly-generated configs from ~/.ssh/vast.d/ that aren't in *keep*."""
    if SSH_CONFIG_DIR.exists():
        for f in SSH_CONFIG_DIR.iterdir():
            if not f.is_file():
                continue
            if f.name in keep:
                continue
            first_line = f.read_text(encoding="utf-8").split("\n", 1)[0]
            if first_line.startswith("# Generated by vastly"):
                f.unlink()


def run_ssh(
    host: str, command: str, *, setup: bool = False, stream: bool = False
) -> subprocess.CompletedProcess[str]:
    """Run an SSH command on *host*.

    Args:
        setup: Use longer timeout options (for setup scripts).
        stream: Print output in real time instead of capturing.
    """
    opts = list(SSH_SETUP_OPTS if setup else SSH_OPTS)
    if vastly.VERBOSE:
        opts.extend(["-o", "LogLevel=DEBUG"])
    cmd = [ssh_program("ssh"), *opts, host, command]

    vastly.verbose(f"ssh {host}: {command[:80]}")

    # Hard timeout: SSH options cover TCP connect and keepalives, but not
    # handshake stalls.  Probe commands get 30s; setup scripts get 10min.
    deadline = 600 if setup else 30

    try:
        if stream:
            return subprocess.run(cmd, text=True, timeout=deadline)
        return subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=deadline,
        )
    except subprocess.TimeoutExpired as e:
        return subprocess.CompletedProcess(
            cmd,
            returncode=1,
            stdout=_as_text(e.stdout),
            stderr=_as_text(e.stderr) or "timeout",
        )


def _as_text(output: bytes | str | None) -> str:
    """Captured output from a TimeoutExpired, as text.

    Python gives it as bytes even when the process ran with text=True.
    """
    if isinstance(output, bytes):
        return output.decode("utf-8", errors="replace")
    return output or ""


def run_scp(
    src: str,
    dest: str,
    *,
    setup: bool = False,
    recursive: bool = False,
    stream: bool = False,
) -> subprocess.CompletedProcess[str]:
    """SCP a file from *src* to *dest*.

    Args:
        setup: Use longer timeout options (for setup scripts).
        recursive: Copy directories recursively.
        stream: Show SCP progress instead of capturing output.
    """
    opts = list(SSH_SETUP_OPTS if setup else SSH_OPTS)
    if vastly.VERBOSE:
        opts.extend(["-o", "LogLevel=DEBUG"])
    flags = ["-r"] if recursive else []
    deadline = 600 if setup else 60
    cmd = [ssh_program("scp"), *flags, *opts, src, dest]

    vastly.verbose(f"scp {src} -> {dest}")

    try:
        if stream:
            return subprocess.run(cmd, text=True, timeout=deadline)
        return subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=deadline,
        )
    except subprocess.TimeoutExpired as e:
        return subprocess.CompletedProcess(
            cmd,
            returncode=1,
            stdout=_as_text(e.stdout),
            stderr=_as_text(e.stderr) or "timeout",
        )
